# Site settings
title: Attar Portfolio
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://attarsinghgill.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Attar Singh"
user_description: "Greetings. I specialise in PHP, MySQL, Laravel and Wordpress development."
user_title: "Web Systems Developer" 
email: "contact.attarsingh@gmail.com"
twitter_username: "lorem_ipsum"
github_username:  "@attarsinghgill"
gplus_username:  "lorem_ipsum"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
